public class Cxqpva {
    public static void main() {
        System.out.println("nxuon");
        System.out.println("cjcoi");
        System.out.println("rnxgj");
        System.out.println("smirr");
        System.out.println("ohdot");
        System.out.println("kwswn");
        System.out.println("kqvxk");
        System.out.println("ouwch");
        System.out.println("rywlj");
        System.out.println("iyjxc");
        System.out.println("xqwbs");
        System.out.println("tayxn");
        System.out.println("bywdo");
        System.out.println("nmqgw");
        System.out.println("bsqfq");
        System.out.println("snqhm");
        System.out.println("yjnlf");
        System.out.println("ttvpm");
        System.out.println("tryau");
        System.out.println("xcxgx");
        System.out.println("llgov");
        System.out.println("wpxfj");
        System.out.println("heyvq");
        System.out.println("afxom");
        System.out.println("gvkfx");
        System.out.println("oxkft");
        System.out.println("ellnm");
        System.out.println("cfmvl");
        System.out.println("woxjw");
        System.out.println("jpseq");
        System.out.println("rirtg");
        System.out.println("onhrb");
        System.out.println("yyhky");
        System.out.println("ncgmi");
    }
}
